# Generated by Django 4.2.2 on 2023-06-22 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campusApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universitycampus',
            name='campus_ID',
            field=models.IntegerField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='universitycampus',
            name='state',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
    ]
